apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: basic
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: ""
  path: ./infra
  sourceRef:
    kind: GitRepository
    name: flux.config
    namespace: flux-system
